### ISSUE TITLE
grant_type=password

### ISSUE THREAD

**Issue by nkarakotas** [bshaffer/oauth2-server-php#248]
Hi, 

When I run the:
 curl -u testclient:testapp -v http://localhost/api/token.php -d 'grant_type=password&username=demouser&password=demopass'

I get:
Fatal error: Uncaught exception 'LogicException' with message 'you must set the user_id on the array returned by getUserDetails'

In token.php I have:
$server->addGrantType(new OAuth2_GrantType_UserCredentials($storage));

// Handle a request for an OAuth2.0 Access Token and send the response to the client
$server->handleTokenRequest(OAuth2_Request::createFromGlobals(), new OAuth2_Response())->send();

Its not clear to me where to set the user_id
Server is:oauth-server-php-0.9

**Comment by belteshazzar** [comment]
For me this problem stemmed from the SQL in the cookbook omitting the user_id. suggest updating the SQL to:

CREATE TABLE oauth_users (user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) NOT NULL, password VARCHAR(2000), first_name VARCHAR(255), last_name VARCHAR(255));

otherwise to fix after the fact add user_id to the oath_users table with [madjennsy](https://github.com/madjennsy)'s solution
