### ISSUE TITLE
Missing token

### ISSUE THREAD

**Issue by ghost** [bshaffer/oauth2-server-php#286]
First of all thanks a lot for this project which makes implementing an OAuth2 server quite easy.

I might be missing something but if I look at this:
https://gist.github.com/sebesvn/8183857

I'm wondering how about instead of just returning false, throwing a 401, something like this:
$response->setError(401, 'missing_token', 'The access token is missing and mandatory');

I'm actually looking for the best way to inform the user when the token is missing.
Thank you for your interest.

**Comment by mdemblani** [comment]
But the new specs say that an invalid_request error should be returned
![image](https://cloud.githubusercontent.com/assets/6511689/11952482/c59f1492-a8be-11e5-908a-0dcd0dec94ea.png)

**Comment by bshaffer** [comment]
there is no "new spec", the document I linked to is the latest version. Also, the error you are referring to above is referring to when authentication has already happened, but the request itself is missing a "required parameter" (i.e. an authorization code grant where the "code" parameter is missing)

I don't like it either, it's very confusing and it's probably the most common bug on here. But I DO believe this is the correct way to implement the spec. But actually since the spec says `SHOULD NOT`, we could get away with having it anyway...
