### ISSUE TITLE
Revoking Access / Refresh Tokens

### ISSUE THREAD

**Issue by flx5** [bshaffer/oauth2-server-php#345]
Hello,
I just got a bit confused about how I should handle the revokation of access tokens.
I just want to show my users the Applications they have authorized and then I want to gove them the possibility to revoke the access token.
So, my first question is how to display all applications a user is using because I couldn't find a matching function in the Storage interfaces (=> Direct MySQL Query?)
Secondly, have I to expire the Access token AND the Refresh token or only one of them?

I also must mention that I am still using the v0.9 as the System Administrator of my school just doesn't have the time to update the server.

**Comment by farooquiyasir** [comment]
I think there should be a proper way of doing this. There is no relationship between an access token and its refresh token. So you cannot delete a refresh token when revoking an access token.

**Comment by farooquiyasir** [comment]
I think it makes sense to revoke access of a client and not an individual access token. So if you are allowing your users to revoke access to the resource server, you will list individual clients in front of them, and will not want to repeat client names if there are more than one access tokens for a client. In that case a simple method can be written to delete / expire all access tokens + refresh token against an individual client.

**Comment by phindmarsh** [comment]
Theres actually an RFC for OAuth token revocation [RFC7009](https://tools.ietf.org/html/rfc7009), which outlines some ideas on how revoking tokens should work from an API perspective.

I've implemented some changes according to this spec in my fork, if you think it might go some way to solving your use-case (and you'd like it in the lib @bshaffer) I'll he happy to issue a PR. It essentially creates a `removeAccessToken()` method on the storage interfaces and adds a revoke endpoint to the controllers. 

I suspect due to the new `removeAccessToken` method this change would probably have to land in a 2.0 release since it is not backwards compatible. Thoughts?

**Comment by bshaffer** [comment]
I'd say you're exactly right on all of your points. This would be an
amazing addition to the library, and is in line with exactly what I was
hoping to add at some point, so your PR would be much appreciated!
