### ISSUE TITLE
Handling endpoints where the access_token is optional

### ISSUE THREAD

**Issue by sarahhenkens** [bshaffer/oauth2-server-php#349]
The library currently has no real non hacky way of handling scenarios where an endpoint is available through the public but can also be used with an access token.

The methods to retrieve and check for token expiration has no way of skipping its error handling if the token is missing, which makes sense when the endpoint has authorization required. 

In the case of an optional authorization, the access token should only be checked if the authorization is in the request object.

**Comment by jellehenkens** [comment]
@bshaffer @phindmarsh

I finally got around to implement this and the solution mentioned only works if I manually pass an instance of `OAuth2\TokenType\Bearer` to the Server constructor. Otherwise Server::getTokenType() always returns null because the tokenType hasn't been set since it gets lazy loaded.
