### ISSUE TITLE
Support for OpenID Connect Authorization Code

### ISSUE THREAD

**Issue by relaxnow** [bshaffer/oauth2-server-php#443]
It appears that in case OpenID Connect is used the id_token is not returned from the token endpoint and as such only the OpenID Connect Implicit flow is supported for now.
I hacked around this for a proof of concept here: https://github.com/relaxnow/oauth2-server-php/commit/fb687325c5f16466ff3ac5ffea57483f42f91c48.

**Comment by justingreerbbi** [comment]
So I ran into the issue today when using openID Connect to sign users into the free Moodle Learning Management System. The `id_token` should be returned when using `response_type=code` if the scope `openid` is present.  

I am going to look into the hack around and the development branch to see if there is simple solution but this is not my forte so fingers crossed.

**Comment by cardonr** [comment]
This problem can be solved by using
`$server->addGrantType(new OAuth2\OpenID\GrantType\AuthorizationCode($storage));`
instead of 
`$server->addGrantType(new OAuth2\GrantType\AuthorizationCode($storage));`
when initializing the server.

The GrantType class `AuthorizationCode` in the OpenID package implements the `createAccessToken` function that add the `id_token` parameter when the **Token** Endpoint is called.

This should be documented on the OpenId Connect page.
http://bshaffer.github.io/oauth2-server-php-docs/overview/openid-connect/

Note that the **Token** EndPoint of the [Demo application](http://brentertainment.com/oauth2/#openid) correctly return the id_token as expected.
