### ISSUE TITLE
checkRestrictedGrantType Functionality (return value)

### ISSUE THREAD

**Issue by bitcalc** [bshaffer/oauth2-server-php#502]
In Storage\Pdo the code disagrees with the interface documentation. The interface says that it should return true when allowed and false when not.

~~~
    public function checkRestrictedGrantType($client_id, $grant_type)
    {
        $details = $this->getClientDetails($client_id);
        if (isset($details['grant_types'])) {
            $grant_types = explode(' ', $details['grant_types']);

            return in_array($grant_type, (array) $grant_types);
        }

        // if grant_types are not defined, then none are restricted
        return true;
    }
~~~
~~~
grant NOT in list = true (allowed)
grant in list = true (allowed) -- wrong
~~~

So the question is, which is right, the code or the docs? I'll override for now, but the return value here needs to change.

**Comment by bshaffer** [comment]
I see your confusion... the title `checkRestrictedGrantType` makes you think `grant_types` in the client details would be a list of *restricted* grant types rather than *allowed* grant types.

The truth is, the `grant_types` field from the client details is the *allowed* grant types, so the `in_array` check is accurate, and everything is happy.

The method might be better written `checkIfGrantTypeIsRestricted`... but that has it's own drawbacks, so the current implementation works for me.  If you have a suggestion on how to clarify this, please submit it here.

So, to reiterate:

```
grant NOT in list = true (allowed)
grant in list = true (allowed) -- correct!
```

**Comment by bitcalc** [comment]
I've just re-read the code above and it works on the same principle as the scopes doesn't it, d'oh! Thinking about the logic behind it all, I can see why you've done it. At first I thought that if I don't want a client to have any grants, then I wouldn't specify any, but then if that was the case, I would just remove them from the client list!

I was (**will**, if I fix my issue) to put in a paragraph about that for both scope and grant types in the docs, if there's me confused, there's going to be someone else...

**Comment by bshaffer** [comment]
Final thought... *Restricted* refers to the fact that the client is restricted *to* the grant types in the list, not restricted *from* them. Very confusing, yes. Perhaps a doc line in the interface would make it clear.
