### ISSUE TITLE
Mistake in JwtAccessToken class

### ISSUE THREAD

**Issue by RomeroMsk** [bshaffer/oauth2-server-php#555]
Here must be `iss` instead of `aud`:
https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/JwtAccessToken.php#L42

**Comment by bshaffer** [comment]
the `iss` in the case of the `JwtAccessToken` is the service, not the client. As the `client_id` denotes the party receiving the access token, I believe `aud` is appropriate here.

If you disagree with this logic, please elaborate.

**Comment by RomeroMsk** [comment]
From [your documentation](http://bshaffer.github.io/oauth2-server-php-docs/grant-types/jwt-bearer/):
> @param $iss The issuer, usually the client_id

And from [official specification](http://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer-07#section-1):
> The JWT MUST contain an "iss" (issuer) claim that contains a unique identifier for the entity that issued the JWT.
> The JWT MUST contain an "aud" (audience) claim containing a value that identifies the authorization server as an intended audience. The token endpoint URL of the authorization server MAY be used as a value for an "aud" element to identify the authorization server as an intended audience of the JWT.

So, I see that `iss` points to issuer (client/service/application who initiate the rerquest), and `aud` points to  audience (for example, identificator of third party auth server or URL for auth).

**Comment by basz** [comment]
hi @bshaffer could you please have a look at https://github.com/zfcampus/zf-oauth2/issues/103

are you able to clarify if I am making a theoretical mistake, apigility has a bug, or a problem exist with the oauth server. thanks a mill

**Comment by bshaffer** [comment]
@RomeroMsk

I think the misunderstanding here is the difference between `JwtAccessToken` and `JwtBearer`.  The client_id for JwtBearer meets the specification that it must be "a unique identifier for the entity that issued the JWT" because in the case of JWTBearer, the *client* has issued the JWT (in order to receive an access token from the OAuth server)

In the case of the `JwtAccessToken`, the issuer is OAuth server. I have made the "aud" to be the client ID. I agree this is not correct, but the JwtBearer spec does not apply here. We cannot make the "aud" the token endpoint, because a `JwtAccessToken` is not *ever* sent to the token endpoint. It is sent to the resource server(s). So "aud" may not apply. The Client ID should be set to "sub" in this case.

@basz what would unbreak this for you? When dealing with the `JwtAccessToken`, I'm not sure an "aud" parameter is relevant.

**Comment by RomeroMsk** [comment]
@bshaffer, oh, I see now. Thanks for pointing that.
