### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by knighti** [bshaffer/oauth2-server-php#577]
hello, i have followed the cookbook by every step. http://bshaffer.github.io/oauth2-server-php-docs/cookbook/

During [Create a Token Controller] when i give it i try to test the files it returns an error which is as follows:
{
"error": "invalid_client",
"error_description": "Client credentials were not found in the headers or body"
}

I have used hurl.it to test the http Authorization

I have also attached the images of the request
![request](https://cloud.githubusercontent.com/assets/12207616/7441164/1ee2ac4e-f0f5-11e4-8d3c-526323d6ac19.PNG)
![request_1](https://cloud.githubusercontent.com/assets/12207616/7441166/1ee8f39c-f0f5-11e4-98b0-acf6db07e4de.PNG)
![response](https://cloud.githubusercontent.com/assets/12207616/7441165/1ee8578e-f0f5-11e4-80db-22927a333a5e.PNG)

Kindly guide me through this.

**Comment by morrizon** [comment]
Be sure that the user and pass match the database. In the cookbook the password is testpass and you're using testsecret. Also, you can add the user and pass as parameters:
client_id: testclient
client_secret: testpass

**Comment by knighti** [comment]
i have saved "testsecret" as "password" in database, that's why i am using it.
I have also tested by adding user and pass as POST parameters but it does not work out.

am i using the right method and way to pass the credentials as in the first picture attached?

**Comment by morrizon** [comment]
Then I think the params must be:

* grant_type: client_credentials
* client_id: testclient
* client_secret: testsecret

When I tested with curl I changed the option -u with that params and worked like a charm:
```
curl http://localhost/token.php -d 'grant_type=client_credentials&client_id=testclient&client_secret=testpass'
```

**Comment by bshaffer** [comment]
hmm, I imagine this could have to do with the HTTP Authorization header bug. However this is fixed in both `Response` objects [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Request.php#L154) and [here](https://github.com/bshaffer/oauth2-server-httpfoundation-bridge/blob/develop/src/OAuth2/HttpFoundationBridge/Request.php#L70)

Can you provide 1) the version of this library you're using, 2) the web server (i.e. Apache, NGinx, etc), 3) php version, and 4) any customizations you've done or other relevant information?

Also, try @morrizon's solution and see if that works.

**Comment by bshaffer** [comment]
Closing this issue because I have not heard back. Please reopen if you can answer the questions above.
