### ISSUE TITLE
Automatic revocation/expiration of access token when sent as query parameter

### ISSUE THREAD

**Issue by xait-arne-trodahl** [bshaffer/oauth2-server-php#581]
Since sending an access token in the URI is insecure, it would be nice to have a config option to automatically revoke/expire an access token if it is sent to the server as a query parameter. Anyone with access to the web server logs will also have access to the token.

**Comment by bshaffer** [comment]
Although sending an access token in the URI is insecure, this is noted under SHOULD NOT and not MUST NOT ([ref](http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html#anchor6)), meaning it's still allowed. 

This being said, removing an access token sent via a query string is not standard, and so would not be an appropriate feature for this library. What would be more standard would be to call the `/token` endpoint ushing HTTP `DELETE` in order to revoke the token.

We could add an `unsetAccessToken` method to `OAuth2\Controller\TokenController`, but that is out of the scope of this issue, so I am closing this.
