### ISSUE TITLE
How flexible can we be with adding new fields to the db tables?

### ISSUE THREAD

**Issue by suj87** [bshaffer/oauth2-server-php#588]
Just wondering how flexible we can be with the tables, in particular the `oauth_clients` and `oauth_users` tables? I'd like to add some additional fields. For now I've created a separate users table and I'm storing additional user details in there (email etc). For the `oauth_clients` table I'd like to add a "client name" field, something presentable to users.

Great library by the way! :+1:

**Comment by ssanders** [comment]
We have added fields to various oauth tables with no problems.

**Comment by suj87** [comment]
I was thinking more in terms of future updates maybe, or something along those lines. But that's good to know, I might just switch over to using the oauth table fully.

**Comment by dsquier** [comment]
The challenge with adding columns is where to draw the line between `oauth_users` and integrating with another (i.e., external) account database. 

If you rely on the `Resource Owner Password Credential` Grant Type, using `oauth_users` is probably not the best approach since it offers very basic password protection (i.e., uses sha, no salts).

Integrating with a separate account database only requires changing `checkUserCredentials()` and `getUser()` in `Pdo.php`, which I'd recommend if you're deploying with the `Resource Owner Password Credential` Grant Type.

Somewhat related, I maintain MySQL DDL for this library (here)[https://github.com/dsquier/oauth2-server-php-mysql]. I'll be updating to the 1.7.1 tag very soon.

**Comment by bshaffer** [comment]
This library abstracts the storage solution from the OAuth2 logic, so that you can customize it however you wish. 

Closing this issue because I'm not sure what else is being asked, but if you have a suggestion as to what would make your situation easier, please feel free to reopen this issue and explain this.
