### ISSUE TITLE
Oauth 2.0 refresh token expiration

### ISSUE THREAD

**Issue by donearh** [bshaffer/oauth2-server-php#628]
I am trying to use Oauth2 system for Android development, but I cannot understand what I have to do if refresh token will be expired. Should I show the login form if the refresh token is outdated, if so at what point do I need to check on a token expired?

Library I use link

Please help me understand after refresh token expired actions.

**Comment by phindmarsh** [comment]
I depends on how you have configured your server to treat re-use or re-issuing of refresh tokens. In our case, our when a refresh token is used a new one is re-issued to replace it. This is done by setting the `always_issue_new_refresh_token` config option to `true` when bootstrapping your server (see [here](https://bshaffer.github.io/oauth2-server-php-docs/grant-types/refresh-token/) for docs). You can continue to use these new refresh tokens as long as you like without asking the user to log in again, provided you are refreshing within the expiry window.

In the case where you don't get new refresh tokens each time, or you wait a sufficient amount of time for the token to expire then you will need to ask the user to log in again to obtain a new one.

Typically, you will want to keep track of when your `access_token` is due to expire and when you get close to that time use your `refresh_token` to get a new one. From here you have two choices:

1. If a new refresh token is issued in the token response, replace your current refresh token and start over
2. If you are allowed to use your refresh token repeatedly, then keep track of the refresh token expiry and request the user to log in when it expires. In most cases your server will have a really long refresh token lifetime if it doesn't enforce one-time-use.

Does that answer your question?

**Comment by donearh** [comment]
Thanks for answer!
Now I understand that if server send me response "error: grant type, error_desc: refresh token is expired" I need to log in user again. Its mean I need to check refresh token on expire on every server request where I use Oauth system.

The course of my actions:
server config: refresh token lifetime 14 days

1. First I try to make a request to the server but the server returns that the access token is expired

2. Then I try to update access token using the refresh token but the server also returns that refresh token is expired

3. Not having received the token, I ask the user to log in again

I m right?

**Comment by phindmarsh** [comment]
In a rough sense, yes you are correct. However from an UX perspective I'd advocate you took a more proactive approach to refreshing your tokens. Rather than sending a request and waiting for it to fail, keep track of the expiry time and do a refresh in the background before it expires. That way the user of your app doesn't have to wait while the request fails, you refresh the token and make the request again. Of course this is entirely up to you, but yes, you are on the right track.

**Comment by donearh** [comment]
You answered my question. You the best!

**Comment by phindmarsh** [comment]
No worries, if you don't have any further questions about this library just close the issue too :smile:

**Comment by skobeo** [comment]
Hum i'm late in this issue, but is it correct to update the refresh token expire date on refresh success, keeping the same refresh token  ?
thanks

**Comment by bshaffer** [comment]
@skobeo no, typically the refresh token should be used once, and then replaced by a new refresh token that comes back with the new access token.

**Comment by skobeo** [comment]
thanks, i'll deal with that. Because i developp an api server, i understand that i have to tell the clients apps to keep the refresh token sended first by api (token password) and to call the refresh token process in case of the ressource process respond "token expires". Lot of traffic if the token is short time, but it seems that this is the right way: it will be stupid i think if the api search about a valid refresh token for an expire token without client request!
thanks a lot and good job for the library, easy to use.
