### ISSUE TITLE
Make it possible to include custom claims in JWT

### ISSUE THREAD

**Issue by hajekj** [bshaffer/oauth2-server-php#631]
It would be great if we could include our custom claims into the JWT when being generated, just like [Google](https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo) or [Microsoft](https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/) do.

**Comment by bshaffer** [comment]
I agree! We made the [`createIDToken`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/OpenID/ResponseType/IdToken.php#L53) method public so that it could be subclassed and customized to do this. 

You could then use dependency injection to add your subclass to the oauth server like this:

```php
$server = new OAuth2\Server($storage, $config, $grantTypes, array(
    'id_token' => new MyIdTokenClass($storage, $storage, array('issuer' => 'yourdomain.com')),
));
```

Does this help?

**Comment by hajekj** [comment]
Thanks a lot, that's exactly what I have been looking for!

**Comment by bshaffer** [comment]
I wish it was easier... if you have an idea how to best do this let us know.

**Comment by francislavoie** [comment]
This is extremely unclean. If I change the IdToken response type, then the other default response types will not be filled in at controller creation time. Also, there's no simple way to get the server's existing config array to pass into my custom IdToken class because the array is protected and the getter is for individual keys in that array.

A thought would be to allow passing in fully qualified class name to be instantiated for the IdToken? I dunno.

I just want to match the OpenID spec which defines profile and email as scopes that should be allowed.
