### ISSUE TITLE
 [Question] How exactly the access/refresh token system works with custom storage

### ISSUE THREAD

**Issue by BrandonShega** [bshaffer/oauth2-server-php#686]
I wrote a custom storage to use for the PHP framework we have implemented and I'm kind of curious as to how exactly access tokens and refresh tokens are set up and used.  I have access tokens being generated successfully but I can generate multiple ones in succession and the existing ones are never overwritten or deleted, it just keeps adding more rows into the database, same with the refresh tokens.  

I'm also curious as to how to generate a new access token based on the refresh token using custom storage.  I'm using the User Credentials grant type by the way.

If anyone can help me out with this I would greatly appreciate it, basically the last piece to finish up our API.

Thanks,
Brandon

**Comment by bshaffer** [comment]
Hello yes! That is the expected behavior. Access tokens are not automatically deleted. They expire, and hang around, and a script to remove them is all you need if you want to keep your DB table small.

As for your second question, if you follow the [`refresh_token`](http://bshaffer.github.io/oauth2-server-php-docs/grant-types/refresh-token/) grant type docs and check out the [demo site](http://brentertainment.com/oauth2/) for the example usage, you should be able to make the expected HTTP request for a refresh token grant. To extend this, just implement the interface and methods of [`OAuth2\Storage\RefreshTokenInterface`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/RefreshTokenInterface.php) in your custom storage and set the grant type to your server object:

```php
use OAuth2\Storage\RefreshTokenInterface;

MyCustomStorage implements RefreshTokenInterface
{
   //...
}
```

and then when setting up your server:

```php
// will automatically detect implemented grant types and set them accordingly
$storage = new MyCustomStorage()
$server = new OAuth2\Server($storage);

// OR ...

// will set the storage for "refresh_token" explicitly, if you'd rather avoid the magic
$server = new OAuth2\Server();
$storage = new MyCustomStorage()
$server->addGrantType($storage, 'refresh_token');
```

**Comment by BrandonShega** [comment]
Oh awesome, I finally figured out how the refresh token works.  I have another quick question, am I able to implement the `TokenControllerInterface` to override those methods?  Our API uses a specific response design and I would like to maintain that instead of using the predefined responses.

**Comment by BrandonShega** [comment]
Never mind, I figured it out :) Thanks for your help!
