### ISSUE TITLE
Automatic Deletion of authorization code

### ISSUE THREAD

**Issue by timyounes** [bshaffer/oauth2-server-php#798]
Hi,

Why is it when i use Authorization Code Grant Type in one process only the generated authorization code in the oauth_authorization_codes table automatically deleted?

**Comment by bshaffer** [comment]
This happens when the [`AuthorizationCode` grant type calls expireAuthorizationCode](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/AuthorizationCode.php#L96). If you're using the `PDO` storage class, the function [removes the PDO from the database](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L217).

If you'd like to change this behavior, extend the `OAuth2\Storage\PDO` class and override the `expireAuthorizationCode` function:

```php
class MyPDO extends OAuth2\Storage\PDO
{
    public function expireAuthorizationCode($code)
    {
        // do nothing
    }
}
```

And then after you've created your server:

```php
$pdo = new MyPDO($dsn);
$server->addStorage($pdo, 'authorization_code'); 
```

**Comment by timyounes** [comment]
Thanks @bshaffer

**Comment by timyounes** [comment]
One more question.. In PDO storage it is require to delete the authorization code?
