### ISSUE TITLE
Authorization code expiration deleted

### ISSUE THREAD

**Issue by timyounes** [bshaffer/oauth2-server-php#799]
Why it is necessary to delete the authorization code after it expires? What is the purpose of it?

**Comment by bshaffer** [comment]
It's just the way this library implements the behavior. Since an authorization code can only be used once, it makes sense to just remove it from the DB.

From [the spec](https://tools.ietf.org/html/rfc6749#section-4.1.2):

> The client MUST NOT use the authorization code
         more than once.  If an authorization code is used more than
         once, the authorization server MUST deny the request

So this is not the same as letting it expire, or returning an error message saying the code is expired. 

If you want to change this behavior, it's entirely within the spec. I would suggest adding a "used" bit to the DB and setting it to true, and checking if it's been used in [`OAuth2\GrantType\AuthorizationCode`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/AuthorizationCode.php#L32)

**Comment by timyounes** [comment]
Thanks @bshaffer. Now I understand what is the purpose of authorization code deletion
