### ISSUE TITLE
Revoke an issued access token

### ISSUE THREAD

**Issue by JosephP91** [bshaffer/oauth2-server-php#817]
Hi everybody,
I am wondering how can I revoke an issued access token. How should structure the controller's action that should handle this kind of request?

**Comment by pjebs** [comment]
Just delete the access token from access_tokens table.

**Comment by JosephP91** [comment]
@pjebs Figured out that there's a handleRevokeRequest method that does the work. Thank you anyway! :)

**Comment by andrewrusselrenner** [comment]
> @pjebs Figured out that there's a handleRevokeRequest method that does the work. Thank you anyway! :)

Hi, sorry to ask. What should I pass to that method? tried using createFromGlobals() doesn't work for me. Thank you.

**Comment by JosephP91** [comment]
Hi @andrewrusselrenner 

The handleRevokeRequest takes a mandatory request parameter and an optional response parameter. If it does not work, I think you are not building the request as it supposed to be built. Unfortunately I do not have access to the code where I used it anymore, so I cannot paste my solution.

**Comment by andrewrusselrenner** [comment]
@JosephP91 Thanks for reply. I've figured it out, it need the post method where the request is from form data where the input key is called "token". Since my client app (which is Nuxtjs with auth module, handled by different person) is just sending post request without including token data, but including token data on Authorization header, any suggestion to workaround this? like grabbed from the Authorization header first then manipulating form-urlencoded request to the hadleRevokeRequest()? I'm not quite sure how to do that. Thank you!

**Comment by JosephP91** [comment]
@andrewrusselrenner if you can't change the way the request is posted, you should adapt the incoming post request to the way oauth2-server-php accepts it. For example, in the controller that handles your revoke request, you should create a oauth2-server-php compliant revoke request in order to make it work with the revoke method.
