### ISSUE TITLE
Invalid Token Audience issue

### ISSUE THREAD

**Issue by nafisqureshi** [bshaffer/oauth2-server-php#950]
Hi,
I am using BlackBerry Spark Communications SDK in my Web application. I have to use OAuth2 Identity manager in it. I am using  bshaffer/oauth2-server-php for this. When creating an access token using this library getting the following response:{"access_token":"337f73db5848dde6d2c76ca2af868487b19991b7","expires_in":3600,"token_type":"bearer","scope":null,"refresh_token":"97c97af533f16aac21e9ea283a5140606f1a669f"}

But when I am passing this access_token to Blackberry SDK it is giving the error "Invalid Token Audience".

**Comment by bshaffer** [comment]
I am not familiar with the Blackberry Spark Communications SDK, so I cannot say what the issue is. But in the following token, there IS no audience, so my guess is the SDK is expecting a JWT Token, which has an audience.

Read more up on [JWTs](https://bshaffer.github.io/oauth2-server-php-docs/overview/jwt-access-tokens/) in the documentation.
